### ISSUE TITLE
br-presenter Parsers cannot be used with EditableProperties

### ISSUE THREAD

**Issue by charliehw** [BladeRunnerJS/brjs#1235]
Parser objects are required to have the isSingleUseParser method, see [EditableProperty.js#L361](https://github.com/BladeRunnerJS/brjs/blob/master/brjs-sdk/sdk/libs/javascript/br-presenter/src/br/presenter/property/EditableProperty.js#L361). However, the Parser interface suggests that this method is optional.

Since the changes to br.implement, these objects no longer have this method so an exception is thrown when changing the value of a Property they are assigned to.

This seems to effect DateParser, LocalisedAmountParser and ThousandsParser in br/presenter/parser/

**Comment by dchambers** [comment]
@charliehw, as you point out, this method is actually supposed to be optional, so I'm confused why it's now causing a problem? When you say that `br.implement()` has changed, do you mean because we never used to use it, and used `br.extend()` instead?

If that's the case, I could understand how if there were no unit tests for these methods, and none of our users used these methods, then I can see how switching from `br.extend()` to `br.implement()` would have caused these problems.

However, from a backwards compatibility point of view, and to continue honoring other parsers that don't implement this optional method, it might be better to change this line of code:

```js
if(oParser.parser.isSingleUseParser()) {
```

to this:

```js
if(oParser.parser.isSingleUseParser && oParser.parser.isSingleUseParser()) {
```

so that the `isSingleUseParser()` method remains optional even for classes that upgrade to `br.implement()`. Would this solution solve the problem you were seeing?

**Comment by charliehw** [comment]
@dchambers, I don't have a full understanding of the history, but I gather `implement` used to act as an `extend`, putting the interface methods on the prototype.

Your proposed fix would make these Parsers work with EditableProperty, but we'd still get an assertion error thrown by this line:

    br.Core.implement(br.presenter.parser.DateParser, br.presenter.parser.Parser);

> Uncaught Error: Class provided does not implement the attributes 'isSingleUseParser' from protocol Parser.

**Comment by dchambers** [comment]
What was confusing me with this issue is why the tests weren't failing if `br.implement()` was failing, and the reason is that `br.implement()` only performs it's verification asynchronously, after the test has finished. I've created a [topiarist.implement() is an anti-pattern](https://github.com/BladeRunnerJS/brjs/issues/1254) issue to deal with this separately.
