### ISSUE TITLE
Let single locale apps recognized the locale in the URL for backwards comp

### ISSUE THREAD

**Issue by thanhc** [BladeRunnerJS/brjs#1259]
For current users who have a single locale app, the locale is part of the url, so if the user has bookmarked this url then on upgrading to the new BRJS where the locale is not part of the URL any more, then there bookmarks wont work anymore.

**Comment by andyberry88** [comment]
Since the URLs have changed this needs to be solved with a redirect and isn't something we're going to be able to fix without either adding some server config or generating extra `index.html` pages with a redirect. Closing this as a `wont-fix` since we're pre 1.0 and it can be solved with relevant server config if any users have bookmarked URLs.
