### ISSUE TITLE
Aliasing not working if you require a class that refers to the interface

### ISSUE THREAD

**Issue by thanhc** [BladeRunnerJS/brjs#1268]
A good example of this is if you create the following alias:
`<alias name="br.locale-switcher" class="br.services.locale.BRLocaleLoadingSwitcher"/>`

And if you try and use this alias then it will continue to use the original class BRLocaleForwardingSwitcher.
In the BRLocaleLoadingSwitcher we require the following:
var LocaleSwitcher = require('br/services/LocaleSwitcher');
 if you remove this line then the alias will work, otherwise it will use the old one.

**Comment by andyberry88** [comment]
@thanhc Is this specific to that Alias? The locale switching page code in the model doesn't get the model to handle the request but instead uses the bundleset itself which could cause a slightly different behaviour. This may be fixed in the `review-plugin-apis-1085` branch since I've refactored that part of the code.

**Comment by dchambers** [comment]
I'm not sure if the changes you are working on will help fix this @andyberry88, but maybe. The problem seems to be that if the chosen concrete class refers to the alias interface, then it can't be used. Since most classes will do this, I can only assume this only happens for CommonJs classes, so we haven't started seeing it yet.

I'll assign to myself, but not start looking at until you've merged your changes.

**Comment by andyberry88** [comment]
This is fixed in ed07d29f3300f60a08bc70e3880603a331553549 which will be merged as part of #1277

**Comment by ccpetercc** [comment]
Tested, works fine
