### ISSUE TITLE
Allow a meaningful version tag to be used

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1290]
At present we version bundle URLs so that browsers are able to indefinitely cache an app's content's. The version identifier we use is either `dev` (in development) or an epoch time like `1426768892800` (in production). Although epoch times are efficient in-memory representations of dates, they are no more efficient to store as strings than ISO style dates, which are easier for administrators to comprehend.

To improve things we'd like to:

  1. Use an easier to comprehend date format like `20150319124132` rather than `1426768892800` (only 1 character more).
  2. Add a `--version-prefix` flag to the `build-app` command that allows a meaningful version prefix (e.g. `3.5.2`) to be provided, causing a composite version of `3.5.2.20150319124132` to be used.

This proposal solves a number of problems:

  * It allows BRJS applications to know what version they are.
  * It allows system administrators looking at web access logs to know both the version number and the build time-stamp of the app being requested.
  * It does this while continuing to prevent people from accidentally generating apps having different contents, but the same version identifier.

**Comment by dchambers** [comment]
@janhancic, is this proposal acceptable for your needs?

**Comment by janhancic** [comment]
Looks good. What would be a reliable way for developers to split that version provided by BJRS into the version-prefix and the timestamp? Would there be a delimiter?

**Comment by janhancic** [comment]
Tagging @adamshone and @sospirited

**Comment by bit-shifter** [comment]
On the face of it, the proposal looks like it might resolve a client support issue too.

**Comment by stevesouth** [comment]
Please consider the work that has already been done with the appcache plugin. We have an appcache.conf file that has two properties, version and devVersion e.g.

appcache.conf
version: 1.1.2-464

and if you want to enable appcache in dev (which you would only do if you were developing a version managment UI), then you can do:

devVersion: 1.0.0

Happy to have a session to talk through how we manage versions on the mobile project. It is probably more than we need for desktop apps, but at we should try and converge on a versioning solution. Perhaps we simply need to move 'version' and 'devVersion' into app.conf, but there may be other options.

**Comment by dchambers** [comment]
Thanks @stevesouth, it sounds like we need to move `version` and `devVersion` into `app.conf`, and start automatically making use of those properties if they are available, for example:

  * The `build-app` command would use the `version` config if available rather than having a `--version-prefix` flag.
  * The `serve` command would use the `devVersion` config if available rather than using a version of `dev`, allowing caching to be tested in dev.

**Comment by janhancic** [comment]
Would you still support `--version-prefix` though? I think I'd rather specify the version with this than modify files with the build scripts. Unless we make "update the conf file and commit" part of the release process I suppose.

**Comment by andyberry88** [comment]
> Thanks @stevesouth, it sounds like we need to move version and devVersion into app.conf, and start automatically making use of those properties if they are available, for example:

It sounds like we're going to make this more complicated that it needs to be. Why can't we accept a `-version` flag for the `serve` & `build` commands and any plugins (e.g. the `AppCache` plugin) that are interested in the current version of the app can get this information from the BRJS model.

**Comment by adamshone** [comment]
I agree with @andyberry88, I would rather be able to specify `version` than `version-prefix`. Whether it's by command line argument or conf file I don't really mind.

The reason is that our app has a convention for versions already, e.g `2.2.0-7046-3b63dc8` (major.minor.patch-build_number-commit). If BRJS is going to make the version available programatically then that's the value I want to use, not `2.2.0-7046-3b63dc8.20150319124132`.

I'd also add that we need to make it available to the JavaScript code in the app, not just available to the plugins via the model. Or were you thinking of reading it from the model in a plugin and then having the plugin expose it via a service, or something?

**Comment by janhancic** [comment]
It's already exposed on `window.$BRJS_APP_VERSION`. This issue is about giving us the option to specify it. Instead of it always being `dev` in dev, and `timestamp` in prod.

**Comment by andyberry88** [comment]
I don't think we should remove the timestamp from the 'version'. It's there as a cache invalidator and IMO should stay otherwise we'll only have other problems with devs having caching issues for 'snapshot' builds. With that in mind @dchambers original suggestion of `--version-prefix` might be better.  The extra change I'm suggesting is that whatever argument we allow should also be added to the serve command which will do the same thing for dev 'mode'. Any plugins that need access to the version should obtain it via the model. Any JS that needs access to the version should get it via the `AppMetaService` which in turn uses the `window.$BRJS_APP_VERSION` from the bundle. 

Note: `window.$BRJS_APP_VERSION` should *NOT* be used directly. There is in fact a comment above it that warns it shouldn't be used and the meta service should be used instead.

**Comment by janhancic** [comment]
> Note: window.$BRJS_APP_VERSION should NOT be used directly. There is in fact a comment above it that warns it shouldn't be used and the meta service should be used instead.

That's new to me. People usually don't look at the code like that. The mobile team uses directly for instance.

**Comment by andyberry88** [comment]
> That's new to me. People usually don't look at the code like that. The mobile team uses directly for instance.

We should make it 'private' then or change the name so it's advertised as an internal variable. Any uses of it should be moved to the meta service otherwise you may find things start breaking if/when we change it.

**Comment by stevesouth** [comment]
I don't think we should have timestamp automatically added to a version prefix as that means developers aren't in 100% control of their versions. For the appcache plugin we still allowed you to have an auto generated timestamp by using $timestamp, I think this is a good idea. e.g.

version: 1.4.5-$timestamp

Please see here, there is lots of info related to this discussion.

https://github.com/BladeRunnerJS/brjs-appcache

**Comment by andyberry88** [comment]
We should see the timestamp as a cache invalidator then and split it from the version string, so URLs look something like `/v/<version>/<timestamp>/<path>`. Or append it to the version in the URL  (`/v/<version>.<timestamp>/<path>`) and remove the timestamp in the meta service so what's returned is the version the developer supplied. Either way the timestamp should be present to ensure that 2 builds with the same version that produce different artefacts don't have the same URLs.

**Comment by dchambers** [comment]
@andyberry88, although the idea of having two levels of cache invalidation within the URLs seems okay on the face of it, it complicates things because at present we either use `dev` in development (a version specifier) or `<timestamp>` in production (a cache invalidator).

I think @stevesouth's idea of allowing people to use versions like `1.4.5-$timestamp` makes it easy for people to avoid creating two artifacts with the same contents, and allows developers to be the final arbiters on what their version specifiers look like, which people seem to like.

**Comment by dchambers** [comment]
@stevesouth, are you happy with us using a `--version` flag for the `serve` and `build-app` commands, rather than having a `version` and `devVersion` property in `app.conf`?

**Comment by andyberry88** [comment]
> it complicates things because at present we either use dev in development (a version specifier) or <timestamp> in production (a cache invalidator).

I don't see the `dev` as a version, I just see it as a fixed cache invalidator that is a known string so we know not to set headers for that request. 

> I think @stevesouth's idea of allowing people to use versions like 1.4.5-$timestamp makes it easy for people to avoid creating two artifacts with the same contents, and allows developers to be the final arbiters on what their version specifiers look like, which people seem to like.

Agreed. But part of the idea of the toolkit is to encourage best practices. Since we're setting far future caching headers everyone will (should) wan't to use the timestamp anyway. I don't understand the need to control the URL structure either. I understand that having a cache invalidator that contains some human readable info so in server logs the asset 'version' can be identified but what is the problem of adding a timestamp invalidator on top of this? It's *not* a version string, its a cache invalidator.
