### ISSUE TITLE
issues remaining from apps living outside SDK

### ISSUE THREAD

**Issue by thanhc** [BladeRunnerJS/brjs#1331]
just so that we don't lose track of it, here are a list of the issues I noticed from #1311 

- only display actual apps on the dashboard, now that you don't need your app in an apps or brjs-apps folder.
- when using polling watcher and running brjs serve --debug, we no longer see the polling log message, instead it just logs "using memozed value for ..." and then waits for the polling interval and then repeats  the scan of the dir.

**Comment by thanhc** [comment]
@andyberry88 there appears to be an issue with apps living outside of an apps or brjs-apps folder, if you try and run brjs serve from within an app which is not in the brjs-apps folder then I've noticed two different issues:
- in one of the cases brjs serve does not output anything and after 5-10 secs it dies with no output.
- in another case I get the following error:
java.lang.ClassCastException: org.bladerunnerjs.api.DirNode cannot be cast to org.bladerunnerjs.api.App
        at org.bladerunnerjs.api.BRJS.userApps(BRJS.java:278)
        at org.bladerunnerjs.utility.UserCommandRunner.checkApplicationLibVersions(UserCommandRunner.java:78
        at org.bladerunnerjs.utility.UserCommandRunner.doRunCommand(UserCommandRunner.java:33)
        at org.bladerunnerjs.utility.UserCommandRunner.run(UserCommandRunner.java:26)

**Comment by andyberry88** [comment]
> in one of the cases brjs serve does not output anything and after 5-10 secs it dies with no output.

This is due to an out of memory issue that sometimes isn't displayed because the JVM crashes as it's severely lacking memory. The root cause of this is using a directory that contains masses of directories that aren't apps (in this case the root of the file system) to hold BRJS apps. The vast amount of apps watched by the file watcher uses enough memory to cause a memory exception. Given we need to watch the directory where apps are living so we can detect new apps we can't selectively watch the individual apps dirs so I've added a change in #1350 that logs a warning if we discover non apps. 

> in another case I get the following error: java.lang.ClassCastException: org.bladerunnerjs.api.DirNode 

I couldn't reproduce this and the stack trace provided doesn't match up with the source code in the branc. @thanhc can you retest ths on #1350?

**Comment by thanhc** [comment]
@andyberry88 regarding the outOfMemory exception, speak to James and Dom, in this case when a user runs brjs serve from within an app we should treat the parent directory as brjs-app folder and instead only serve the single app in which case we wont need to watch the whole directory

**Comment by andyberry88** [comment]
> instead only serve the single app in which case we wont need to watch the whole directory

The problem comes when commands want to create new apps. If the dashboard is used to create an app where do we put it, or do we now add guards around every place where apps can be accessed to make it work in 'single app mode'.
This is an edge case we've always had, its just been tested and brought up now because of the separating the apps dir. Given a warning is logged if we find non app directories inside of where apps live  which explains exactly whats caused the problem I don't see this as an issue.
