### ISSUE TITLE
apps should be created inside the working dir

### ISSUE THREAD

**Issue by james-s-turner** [BladeRunnerJS/brjs#1386]
OSX 10.9.4
Steps to reproduce:
1. Install BRJS in directory $BRJS_HOME
2. Create directory $APP_HOME and open command prompt 
3. Execute command $BRJS_HOME/sdk/brjs create-app wibble
4. App is created in $BRJS_HOME/sdk/brjs-apps/wibble

Should be created in directory I ran command from.

**Comment by andyberry88** [comment]
> Should be created in directory I can command from.

This is different from the behaviour previously agreed - although it does make sense that this should be the behaviour.

To avoid any confusion what we previously decided on was:
1. if we're inside an app directory then apps live inside the parent directory of that app
2. if we can't find an app traverse up the directory tree to find `brjs-apps`
3. if we can't find a parent `brjs-apps` then use `brjs-apps` that live next to the `sdk`.

To support `Should be created in directory I can command from.` we would need to change `#3` so that we fall back to the current working directory as the location for apps.

**Comment by james-s-turner** [comment]
Two points:
1. Even according to rule #3 the app is created in the wrong place. It should be inside a brjs-apps directory beside the sdk directory NOT inside it.
2. I take the point about the original decision. It would be nice if we could do what was stated. Any idea how much effort it would be.

**Comment by andyberry88** [comment]
> Even according to rule #3 the app is created in the wrong place. It should be inside a brjs-apps directory "next to" the sdk directory NOT under it.

True, missed that point. That's definitely not what we were after.

> I take the point about the original decision. It would be nice if we could do what was stated. Any idea how much effort it would be.

I agree your suggestion makes more sense, I just wanted to clarify what the current expected behaviour was to avoid confusion. It should be reasonably trivial to make the change. I'd suggest we do it before 1.0.
