### ISSUE TITLE
1.0 RC2 Feedback

### ISSUE THREAD

**Issue by dchambers** [BladeRunnerJS/brjs#1435]
Here's the 1.0 RC2 feedback from @janhancic:

  1.  `require()` invocations in some tests had to be moved from `describe()` to within `beforeEach()` (**needs further investigation**).
  1.  `Clock.install()` now required (**known breaking change**).
  1.  Templates required directly from the template service now have their IDs stripped off, in the same way that used to occur for Presenter components (**known breaking change**).
  1.  Alias schema URL warnings (**known issue, but CT should be updated so only user files generate warnings**).
  1.  Some tests were relying on private member variables (**not an issue**).

I think we'll be good to release 1.0 once we understand issue 1, and are able to either fix it or document it as a known issue. @andyberry88, could you investigate please?

**Comment by andyberry88** [comment]
> require() invocations in some tests had to be moved from describe() to within beforeEach() (needs further investigation).

This is a side effect of us now not caching the returned value from `require(service!some-service)`. GWTTestRunner automatically clears down the service registry before every test. Since we now go back to the service registry every time a service is required if the service registry is cleared down new services are created when requested.

@dchambers is adding a section to the release notes to highlight this change.

**Comment by andyberry88** [comment]
Only `#1` needs to be addressed here and it fixed by the release note change in #1439.
