### ISSUE TITLE
Refactor and host Dans 'CONNETO' app on the BRJS site

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#1461]
Refactor, code review and add a new languages to @thecapdan 'CONNECTO' app. We should also host this somewhere and publicise it.

**Comment by thecapdan** [comment]
repo added here: https://github.com/BladeRunnerJS/connecto
app can be viewed here: https://bladerunnerjs.github.io/connecto/

**Comment by dchambers** [comment]
@thecapdan, here's some feedback:

  1. You need some instructions in your `README.md` that explain how to use the app.
  2. I think it would make sense for the `README.md` to specifically refer people to [`default-aspect/index.html`](https://github.com/BladeRunnerJS/connecto/blob/master/default-aspect/index.html) and [`default-aspect/src/lang/App.js`](https://github.com/BladeRunnerJS/connecto/blob/master/default-aspect/src/lang/App.js) as being good starting points for understanding the app.
  3. Do you need a `WEB-INF` directory or is this something that could be deleted?
  4. Why is your require-prefix `lang` rather than something more obvious like `connecto`?
  5. All of the files within `default-aspect/resources` are just starter template files; I don't know if other people think these should be deleted or not?

**Comment by thecapdan** [comment]
changes mentioned above have been done in connecto master branch https://github.com/BladeRunnerJS/connecto/commits/master
