### ISSUE TITLE
Not able to share themes across Aspects

### ISSUE THREAD

**Issue by amrishn** [BladeRunnerJS/brjs#1509]
I have one requirement where I want to share themes across aspects. One way would be to add it to each aspect. Is there any cleaner way so that We can share themes across different aspects. 
So if I have default-aspect and a theme, I can reuse that theme into my login aspect.
I took a look into CssTagHandlerPlugin.java and found that by default it takes request path, so in case of login aspect it searches for theme under login aspect.

**Comment by andyberry88** [comment]
Hi @amrishn, CSS is handled in the same way as any other resource in that when you view an Aspect only the files from that Aspect and any dependent BladeSets and Blades are bundled. There is no way to share any resources in one Aspect with another Aspect.

Just as you would put any HTML, i18n config etc. in the same Blade as your JavaScript, CSS should also live in the Blade. You can either put it inside `<blade>/resources/`, in which case it will be bundled if any JS class in the Blade is used, or inside `<blade>/src/....` next to the JavaScript files, where it will then only be bundled if the JavaScript in the same directory is used. The Aspect should then only have the styling necessary to arrange the Blades and any override styling.

It is sometimes necessary to share a minimal amount of CSS between Aspects. At the moment the only way to do this is to create a Library or Blade for your shared CSS that contains an empty JS class. You can then 'require' the empty Library/Blade class from your Aspects so that the dependency analysis bundles the CSS from that location. https://github.com/BladeRunnerJS/brjs/issues/767 will make this process much easier but I can't say when this feature will be added.

**Comment by amrishn** [comment]
Thanks @andyberry88  for your comments. I realized that we can't share css ( or any other libraries)  between aspects. 
I feel that there should be some feature which can let us to achive this. As if we want to share something between blades, we put them at Bladeset level. If we want to share something between  Bladesets we keep them at default-aspect level. 
Current implemenation of BRJS treats aspects as two different apps with-in a single app. 
Anyways that is my thought, I will provide a library for shared css. Thanks Again.
