### ISSUE TITLE
Generate build of an app using specific version number instead of datetime

### ISSUE THREAD

**Issue by saifmd4u** [BladeRunnerJS/brjs#1511]
I have been using bladerunnerjs a lot recently. I was getting little frustrated by the fact that, building an app will always create a new folder for eg:.. builds\booking\v\20150902113748

Is it possible for me to enforce a specifi version number with "brjs build-app" command. This will help us reduce some of the manual steps.

**Comment by andyberry88** [comment]
Hi @saifmd4u, you can specify a version number by using the `-v` flag (for example `brjs build myApp -v 1.2.3`), however this will still append the timestamp to the version so you'll end up with a version of `1.2.3-20150902113748`.

We've taken this approach to ensure that *every* version of an app that's built has a different version number string, even if the `<major>.<minor>.<patch>` part is the same. This then allows `Max-Age` and `Expires` headers for any versioned assets to be set to 1 year and guarantees that if a new version is built, even with the same version, the new assets will be loaded rather than the cached versions being used. This approach can hugely decrease the load on production servers and improve app load time.

What manual steps are you performing? Perhaps the same thing can be achieved a slightly different way without manual steps, or by using a BRJS plugin.

**Comment by andyberry88** [comment]
@saifmd4u Does the above answer your question? Are you happy for this to be closed?

**Comment by saifmd4u** [comment]
As of now I am not using automation deployment, so for deploying a build i will have to delete existing contents first before copying the new ones. Any way I agree with what you are saying about caching issue. Thanks for the update and yes you can close the issue.
