### ISSUE TITLE
Calculate i18n dependencies for html templates and XML config

### ISSUE THREAD

**Issue by thecapdan** [BladeRunnerJS/brjs#1573]
Any i18n translations used in HTML templates and XML config should be bundled in the i18n bundle.

**Comment by andyberry88** [comment]
Having taken a look at this it's not something that's as trivial as it seems. The multiple files defining a single translation goes against how the model has been designed - one require path is one file. Since this issue came about after the changes in #1564 and has since been fixed by #1582 closing as a `wontfix`.
