### ISSUE TITLE
Remove the /<locale> from the end of URLs if there is only a single locale

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#692]
If an app only has a single URL /, rather than /en, should be used as the app home page.

As part of this the logic to do with the request path for bundles should be moved to a centralised place and the '../' is only added to bundle URLs if the content is being served from /app/<locale>.

**Comment by minlokchan** [comment]
More information can be found here:  http://yourls.caplin.com/9

**Comment by dchambers** [comment]
I've now investigated whether we do still really need to use a `<base/>` tag anymore, and proved that we don't (see the [deprecate-base-tag](https://github.com/BladeRunnerJS/brjs/tree/deprecate-base-tag) branch for example). Instead, it turns out there is a compromise to be made:

  1. If we don't have a base tag then `unbundled-resources` URLs break.
  2. If we do have a base tag then [route URLs break](https://github.com/BladeRunnerJS/brjs/issues/1059).

It happens that not requiring single-locale apps to include the locale in their URL will reduce the likelihood that developers encounter either of these problems, but in some ways will make it worse since library code and shared templates that need to work in both single-locale and multi-locale apps will need a dynamic solution.

My vote is to break `unbundled-resources` URLs by default for the following reasons:

  1. The `unbundled-resources` content plug-in is the only content plug-in that end-developers need to be aware of, but for which we don't provide a tag to simplify access to it's resources.
  1. `unbundled-resources` URLs are usually found within HTML only, whereas route URLs are also commonly found within both HTML and JavaScript, increasing the chance that end-developers need to use a programmatic solution, in addition to a simple tag.

@james-shaw-turner / @andyberry88 / @thecapdan: what do you think?

**Comment by stevesouth** [comment]
I have had issues this week with caching in chrome. I still believe
versioning is useful in dev mode.

**Comment by dchambers** [comment]
Hi @stevesouth, we're not talking about getting rid of versioning here, we're talking about both removing the need for the locale to appear in the URL of single locale apps, and removing the need for a `<base/>` tag.

In BladeRunner we used to use a `<base/>` tag to allow us to have versioned URLs, but in BladeRunnerJS we've solved that differently, though we still ended up keeping a `<base/>` tag for other reasons, and that was probably a dubious decision, which I'm arguing against here.

**Comment by dchambers** [comment]
Just noticed the 'index.html' page within the dashboard:

```
<@js.bundle dev-minifier="combined"@/>
<script type="text/javascript" src="../v/dev/unbundled-resources/browserCheck.js"></script>
<script type="text/javascript" src="../v/dev/unbundled-resources/releaseNoteUtils.js"></script>
		
<@css.bundle theme="standard"@/>
<link type="text/css" rel="stylesheet" media="screen" href="../v/dev/unbundled-resources/standard-theme/typography.css" />
```

which shows that we are going to need a `<@unbundled-resources@/>` tag regardless, since in the code snippet above the version name (`dev`) is being hard coded, so that this app won't work in production. The fact that the dashboard will never be put into production is just good luck of course.

**Comment by dchambers** [comment]
@lukepage, can you confirm that the your app is a single-locale app, since otherwise this improvement isn't going to help you?

**Comment by lukeapage** [comment]
No it isnt single locale, its multi.
our problem is that upgrading is a pain since we a) had url routers using the last directory on the url as a username (for test/development) - solved by changing to a url param b) we have heavy duty firewalls where we have to specify every url, so url changes are a pain.

Also what if our business owners dont like the url being in the url?

i dont understand why the locale directories were put in - why you dont jyst dynamically load the right i18n bundle in a single html page? We dont know the locale till we connect to streamlink and thats got to be common - at the moment we fully load, connect and then reload a different url. We used to fully liad, set a cookie and the reload the same url.

When i look st the generated index files they all seem identical apart from the path to the i18n files - seems a bit crazy.

Your injecting a script tag in the first page anyway, why not inject a script tag that chooses the file to load, avoid redirects and locale directories.

**Comment by lukeapage** [comment]
We think we can adapt to the changes so its no longer high priority - looked scary at first. Min you can reduce the pri of the caplin issue (ive been away). Excuse typos, on a mobile.

**Comment by lukeapage** [comment]
We also use unbundled resources for alot more than ct - we would need at least a tag, i think we reference unbundled resources from multiple places too, not just index html.

**Comment by andyberry88** [comment]
// @BladeRunnerJS/caplin-support  @minlokchan

**Comment by dchambers** [comment]
Hi @lukeapage,

Even though you think you can adapt to the URL changes, it's still worth addressing some of your points for posterity, and in case other people have similar concerns:

> i dont understand why the locale directories were put in - why you dont jyst dynamically load the right i18n bundle in a single html page?

The reason we now require apps (shortly, multi-locale apps only) to have the locale in the URL is to be able to support [static file deployment](https://github.com/BladeRunnerJS/brjs/issues/18). There were other options that wouldn't have required a URL change discussed in the [strawman proposal](https://github.com/BladeRunnerJS/brjs/wiki/Static-File-Deployment-Design-Issues-&-Strawman), but these were rejected as they all had notable downsides.

> We dont know the locale till we connect to streamlink and thats got to be common - at the moment we fully load, connect and then reload a different url. We used to fully liad, set a cookie and the reload the same url.

No, I've honestly never heard of any anybody doing this before, and find it a strange thing to be doing. I can only assume that you are considering the user's locale as being part of the permissioned data that gets streamed to the client.

The way it's usually done is like this, where the user is free to choose the locale they prefer:

  1. An app supports a fixed number of locales.
  2. The first time the user loads the app they are given the best-fit locale based on their browser's `Accept-Language` headers.
  3. They are then free to change locale, which causes a cookie to be set, and the main URL (without the locale in it) to be re-loaded.
  4. If they load the app in the future they will immediately use the locale they set in their cookie, but will still have the option to switch again.

> When i look st the generated index files they all seem identical apart from the path to the i18n files - seems a bit crazy.

Yes, it is slightly odd, but probably makes sense once our need to support [static file deployment](https://github.com/BladeRunnerJS/brjs/issues/18) is taken into account.

> Your injecting a script tag in the first page anyway, why not inject a script tag that chooses the file to load, avoid redirects and locale directories.

This was actually one of the options discussed in the [strawman proposal](https://github.com/BladeRunnerJS/brjs/wiki/Static-File-Deployment-Design-Issues-&-Strawman), but was rejected because it would cause the index page to become difficult for developers to understand, whereas at the moment the index page has useful didactic qualities.

> We also use unbundled resources for alot more than ct - we would need at least a tag, i think we reference unbundled resources from multiple places too, not just index html.

I've already added [support for an `<@unbundled-resources@/>` tag](https://github.com/BladeRunnerJS/brjs/commit/37858ba293f67910727ec081aaaeac2f330aaf31), but it's very basic in that it can only be used within app index pages, and can only refer to `unbundled-resources` within the top-level app. It would therefore be good to hear how else you're making use of that feature, so we can better support you.

It is worth noting however that the need for `unbundled-resources` in BladeRunnerJS is diminished compared to BladeRunner, where exotic CSS resources could not be referred to within bundled style-sheets.

**Comment by dchambers** [comment]
This is fixed by #1173.

**Comment by dchambers** [comment]
I've created #1174 to discuss plans to enhance the `<@unbundled-resources@/>` tag.

**Comment by lukeapage** [comment]
> No, I've honestly never heard of any anybody doing this before, and find it a strange thing to be doing. I can only assume that you are considering the user's locale as being part of the permissioned data that gets streamed to the client.

Your workflow excludes the possibility of someone using the app on multiple devices or devices that are not their own.

Every web app I have worked on has user preferences stored serverside (so they are not lost on different computers). The language setting is one of those settings, why should it be required to be stored in a cookie? Why should language be different from any other setting? The ideal situation is a bootstrapper during the load phase that establishes the app, but doesn't use i18n or layout or settings and then which populates those after bootstrap.

We also take advantage of the computers language and the cookie in order to guess the correct language and thats great, but then the cookie might be wrong when we have finally logged in.

> This was actually one of the options discussed in the strawman proposal, but was rejected because it would cause the index page to become difficult for developers to understand, whereas at the moment the index page has useful didactic qualities.

Well, I understand it is not completely crazy, and having a static file structure is great, but your approach at the moment has several downsides
a) Inflexible for people wanting to take a different approach (without work-arounds) - for instance, I cannot override the main index page to change behaviour. I cannot access the base tag within the main index page (I was trying to get the base tag url out in the locale utility js), which would be required to workaround issues where the url needs to base tag to understand which url to navigate too.
b) An un-necessary redirect every time someone logs in
c) We have to now try and detect if someone has changed the language via the url or if they have got navigated into the wrong language
d) the url is for end users, we shouldn't be adding technical artifacts

And those downsides vs `the index page to become difficult for developers to understand` which I do not understand, it seems a bit ridiculous that you have a system where most of your existing customers are highly complex web applications with thousands of files and hundreds of templates and a developer can't understand that i18n is added dynamically in a single script tag in the main index page?

However, although its not the choice I would have made, we can adapt to these changes.

We do not use the css bundling because of lack of support for a preprocessor and because we want seperate css compiled using an ie8 variable in the preprocessor to be included in IE8 using conditional comments - so we compile to css files and reference them from the index file.

We are using unbundled-resources also for a couple of html pages, but one of those we are refactoring because the new brjs no longer replaces tags in html files inside unbundled_resources (when it used to).

So, thats css, layouts and a couple of html files we use from unbundled resources. Further files are references from the css and html relatively so of course they will be okay.

**Comment by lukeapage** [comment]
also on the subject of i18n have you considered enforcing i18n to be used with whole strings and then replacing `br.i18n()` calls with the actual string before minifying? That would be the idea solution to i18n (though of course doesn't effect this conversation since it just moved the i18n from a seperate file into the js)

**Comment by dchambers** [comment]
> Your workflow excludes the possibility of someone using the app on multiple devices or devices that are not their own.

Actually, it doesn't. While I admit that our current work-flow isn't optimized for the first time a new device is used, the straw-man did consider the need for customization by end-developers when it asked the question:

> Should the locale switching page be editable by the user, or held internally?

The answer to that question was that we decided that developers should be able to modify the switching logic (the JavaScript) rather than the entire page itself, as this was much simpler for us to implement. You can achieve this yourself by overriding the `br-local-utility` library within your own app, and this will afford you the opportunity to switch locales based on preferences stored on a server.

Moreover, if you genuinely find locale-forwarding using URLs distasteful, you can probably manage to dynamically insert the necessary tags using JavaScript alone, and if you choose to go this route your points _a_, _b_, _c_ and _d_ all cease to be relevant.

> And those downsides vs the index page to become difficult for developers to understand which I do not understand, it seems a bit ridiculous that you have a system where most of your existing customers are highly complex web applications with thousands of files and hundreds of templates and a developer can't understand that i18n is added dynamically in a single script tag in the main index page?

Actually, all of my experience while working at Caplin has taught me the opposite. As a highly experienced web developer you probably aren't aware just how much tacit knowledge you posses. Many of our clients have traditionally employed developers from Java and .NET backgrounds rather than web developers, and stuff like this which you and I find easy, they struggle with.

> We do not use the css bundling because of lack of support for a preprocessor and because we want seperate css compiled using an ie8 variable in the preprocessor to be included in IE8 using conditional comments - so we compile to css files and reference them from the index file.

> We are using unbundled-resources also for a couple of html pages, but one of those we are refactoring because the new brjs no longer replaces tags in html files inside unbundled_resources (when it used to).

> So, thats css, layouts and a couple of html files we use from unbundled resources. Further files are references from the css and html relatively so of course they will be okay.

Okay, this is all really helpful information which I'll feed into any design decisions we make.

**Comment by dchambers** [comment]
> also on the subject of i18n have you considered enforcing i18n to be used with whole strings and then replacing br.i18n() calls with the actual string before minifying? That would be the idea solution to i18n (though of course doesn't effect this conversation since it just moved the i18n from a seperate file into the js)

This is a really interesting idea. I've never considered it, and can't say I know how easy it would be for us to do, but it definitely sounds interesting in theory. Perhaps you'd like to create a new issue so we can track it?

**Comment by lukeapage** [comment]
> You can achieve this yourself by overriding the br-local-utility library within your own app, and this will afford you the opportunity to switch locales based on preferences stored on a server.

Yes, I've done that and it did occur to me I could manually insert the tags or add bootstrap code to get the preferences.. 

manually inserting tags - I wouldn't want to do because it seems to stray too far from brjs and for little benefit - All my arguments one way or the other are tbh minor concerns and certainly the performance is minor, so we couldn't justify spending the time to our business owners when also making something that might be harder to upgrade.

bootstrap code in the first index page - Again, I considered, and it would make language switching nicer, but it would also make that first index file larger and take much longer before it redirected - at which point it would then have to reload the javascript and reconnect - so for this one I'm not sure the benefits outweight the performance loss costs when language switching (which happens less often than logging in on another project.

> Perhaps you'd like to create a new issue so we can track it?

I'm leaving the client project using brjs in a month and a half, so probably best someone else creates it.

**Comment by dchambers** [comment]
@lukeapage, I've [made some improvements](https://github.com/BladeRunnerJS/brjs/pull/1180) to simplify how the customization of the _locale-switching_ mechanism. Updates to the documentation to follow...

**Comment by andyberry88** [comment]
@dchambers are we hoping to get this in the 0.15 release?

**Comment by dchambers** [comment]
I don't think so. @james-shaw-turner has asked for us to release a 0.15 ASAP.

**Comment by andyberry88** [comment]
:+1: that's what I thought.

**Comment by james-s-turner** [comment]
Yup - my understanding from this morning standup was that we would
release.15 without local changes.
Also apart from that I think we don't have any backward breaking changes
(apart from Java plugins). Is that correct?

**Comment by andyberry88** [comment]
Yep. There'll be changes to the Java API but v0.14.x apps should still be compatible.

**Comment by thanhc** [comment]
single locale apps no longer had the locale in the url
