### ISSUE TITLE
Jasmine JavaScript errors aren't handled the same in development as they are in production

### ISSUE THREAD

**Issue by thecapdan** [BladeRunnerJS/brjs#703]
When running an app with a javascript error on brjs serve, I was given an error in the console but the application continued to work as normal:

"Uncaught ReferenceError: TestCase is not defined" 

But when I build a war and run it on tomcat, the application fails to load correctly with the following errors:

"Uncaught ReferenceError: TestCase is not defined"
"Uncaught Error: No definition for module br/ServiceRegistry could be found in the global top level."

**Comment by ioanalianabalas** [comment]
This is a non-issue, as it is caused by how the bundle is handled. The definition of the module is after the reference to a TestCase. Seeing as how this reference could not be solved, it throws an exception, meaning that the line containing the definition of the module is never run.

**Comment by thecapdan** [comment]
Ok, I'm happy to close this on the grounds that it is not currently based on a valid use case - will re raise if I can find a real use case

**Comment by dchambers** [comment]
I'm re-opening as I'd still like to know why the code behaves differently in dev and prod. This doesn't need to be investigated for 1.0 necessarily, so I'm happy for it to be moved out of that milestone.

**Comment by andyberry88** [comment]
The code doesn't behave differently, its due to having all the code in a single bundle vs separate script tags.
- In dev each class is in it's own file. If an exception is thrown during the parsing of one class every other class will continue to be loaded since they are separate script tags.
- In prod we use a single bundle. Once the exception is thrown during the definition of one class every class below that definition will not be parsed since they are all now loaded via a single script tag.

e.g.

```
file1:
  define A  <---- an exception here doesn't prevent B from being defined
file2:
  define B
```
vs
```
single bundle:
define A  <---- an exception here prevents B and C from being defined
  define B
  define C
```

For this particular scenario `Jasmine` is throwing an exception when it's defined and `appns/Class` has a dependency on `br/ServiceRegistry`. Due to the ordering in the dependency tree `appns/Class` is defined first, followed by `Jasmine`, followed by `br/ServiceRegistry`. With separate script tags all classes are defined regardless of exceptions thrown when defining other classes. With a single script tag (bundled classes) an exception when defining one class, in this case `Jasmine`, prevents everything below it being defined - so `appns/Class` is defined and can be used from `index.html`, but once that tries to require `br/ServiceRegistry` it fails due to the exception thrown earlier which prevented the class from being defined.
