### ISSUE TITLE
move the bundlePath token logic into a single shared location

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#775]
So we can support bundle path tags in XML and HTML content (#753) we have special logic in those bundlers to replace `@bundlePath@` with the real path. This logic should be removed from the specific bundlers and be a single mechanism that is run on every bundler (similar to JNDI tokens but not dynamically applied by a filter). 

`unversionedBundlePath`, and possibly `appVersion`, should also be added as supported tokens,

This ties in with #749 where the same token format is used but any tokens that start with `BRJS.` are 'system' tokens and are not replaced via properties files but handled by the model instead.

**Comment by dchambers** [comment]
Hi @andyberry88, I'm struggling to understand the acceptance criteria for this issue. Any chance you could update the main description to reflect the final acceptance criteria?

**Comment by andyberry88** [comment]
@dchambers I've updated the title and description. Can you have a read and see if that makes sense now?

**Comment by dchambers** [comment]
Okay, I think I get it know. So we're saying:

  1. The `@bundlePath@` token should work in all bundlers, and not just the XML and HTML bundlers.
  1. Support for `@unversionedBundlePath@` and `@appVersion@` tokens should also be added.
  1. We need to consider whether _user-defined tokens_ (of the form `@[A-Z\.]+@`) should be handled using the same mechanism or not.

BTW, IMO opinion it makes sense that _user-defined tokens_ retain their unique visual format, so that it's obvious to developers what type of token they are looking at.

**Comment by andyberry88** [comment]
> BTW, IMO opinion it makes sense that user-defined tokens retain their unique visual format, so that it's obvious to developers what type of token they are looking at.

Does it matter if a token is user defined or not? There's a small amount of tokens that can be seen as having default values (and that shouldn't be changed/overridden) and the user is free to add more as they wish.

To me it seems like the 2 distinctions we have are 'dynamic' and 'static' tokens where 'static' tokens *must* be replaced at build time when building a war and 'dynamic' tokens can be replaced via a JNDI lookup. 

We could use a simple mechanism where if building a war we replace any tokens we know the value of at build time (possibly from a 'war.properties' file?) and emit a warning about tokens that don't have a value to replace. The rest of the tokens are then replaced via a JNDI lookup at runtime.
When building static files all values must be defined so we can replace them all statically and in this scenario we fail if a replacement can't be found.
Using this mechanism we would only have a single token format and a well defined workflow for getting token values.

**Comment by dchambers** [comment]
> To me it seems like the 2 distinctions we have are 'dynamic' and 'static' tokens where 'static' tokens must be replaced at build time when building a war and 'dynamic' tokens can be replaced via a JNDI lookup.

Interesting. I don't see there being two types of token in this case but two types of value provision, since the value for a user-defined token can be provided statically or dynamically as the developer sees fit, and where the same token may be provided statically by some developers and dynamically by others.

Again though, the fact we're having this conversation makes me feel like we should agree on a well defined set of acceptance criteria before doing any more work on this issue.

**Comment by andyberry88** [comment]
> we should agree on a well defined set of acceptance criteria before doing any more work on this issue.

Agreed. The work I've done so far was some refactoring around the current token replacing mechanism and using a reader rather than buffering all the content. The plan now is to write up a proposal for static tokens which we can discuss later today.

**Comment by dchambers** [comment]
:+1:

**Comment by thecapdan** [comment]
move acceptance criteria to issue description, please. ty

**Comment by andyberry88** [comment]
@thecapdan done. Most of the criteria is in #749 since this is an extension to that.

**Comment by thecapdan** [comment]
done as part of https://github.com/BladeRunnerJS/brjs/pull/1483

reviewed and tested. will move once the encoding issue in the PR above is fixed and merged
