### ISSUE TITLE
allows apps to push users to the locale forwarder if app locale doesnt match the users choice

### ISSUE THREAD

**Issue by andyberry88** [BladeRunnerJS/brjs#804]
Create a mechanism that (optionally) allows apps to push users back to the locale forwarder if the current app locale doesn't match the locale calculated from the locale cookie and browser headers.

This will allow users to refresh the page after changing their locale since after the refresh the locales wont match and the browser will be sent to the locale forwarder. It also means if locale pages are bookmarked the correct locale will ultimately still be used.

**Comment by dchambers** [comment]
Now that #1186 has been done, we should add the extra requirement that `LocaleSwitcher.switch()` should work regardless of when it's invoked (i.e. it should be possible to invoke it from the app too, in addition to the locale-switching page), so that the following code should work:

```js
require('br.locale-provider').setActiveLocale(myLocale);
require('br.locale-switcher').switch();
```

for all three types of app:

  1. Single-Locale Apps
  1. Multil-Locale Apps (forwarding style)
  1. Multil-Locale Apps (non-forwarding style)

**Comment by thanhc** [comment]
tested locale switching with both forwarding and non-forwarding styles and both works, although found an issue with aliasing while testing this, raised #1268
