### ISSUE TITLE
Can't run tests with --report flag on some IE11 machines

### ISSUE THREAD

**Issue by thecapdan** [BladeRunnerJS/brjs#825]
we get:

Writing HTML reports to ../test-results/html.
ERROR: Errors while applying transformations: Fatal error during transformation
Error:
Error running tests.
Caused by: javax.xml.transform.TransformerException: D:\go\pipelines\ct-brjs-develop\ct-core\test-results\html\Mozilla\50_(Windows_NT_61;_WOW64;_Trident\70;_rv:110)_like_Gecko__Windows\package-frame.html (The filename, directory name, or volume label syntax is incorrect)

This may also impact running tests via the dashboard, as it also generates html reports

**Comment by ioanalianabalas** [comment]
I am encountering this issue every time I try running tests with the --report flag on IE11.

The problem seems to be related to Ant, as the line that is failing is `project.executeTarget("junitreport");` from `TestRunner.java`. I have investigated this issue and the most commonly suggested solution is to change to Ant 1.9.0 but I tried this with no success. Another proposed solution is to set the following property:

`System.setProperty("javax.xml.transform.TransformerFactory", "org.apache.xalan.processor.TransformerFactoryImpl");`

but we already have this in place (due to another bug, please see code for details) and this didn't help either.

Also, the string Mozilla\50_(Windows_NT_61;_WOW64;_Trident\ is actually due to the IE11 user agent.

**Comment by ioanalianabalas** [comment]
Fixed by #1199.
